host = "127.0.0.1"
rpcpass = "123"
rpcuser = "admin1"
port = 8333
rpcport = 9332
db = "/home/isaac2/programming/pynode2/chaindb"
chain = "bitcoin_testnet"
datadir = "/home/isaac2/programming/pynode2"
ui_address = "localhost:8888"
